# Generated by Django 4.1.5 on 2023-01-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_customer'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='fName',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='lName',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordermodel'),
        ),
    ]
