# Generated by Django 4.1.5 on 2023-01-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_addressmodel_fname_addressmodel_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='current_address',
            field=models.BooleanField(default=False),
        ),
    ]
