# Generated by Django 4.1.5 on 2023-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_addressmodel_current_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='email',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='DateOfBirth',
            field=models.DateField(default="2023-01-23"),
            preserve_default=False,
        ),
    ]
