# Generated by Django 4.1.5 on 2023-01-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customermodel_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='name',
        ),
    ]
