# Generated by Django 4.1.5 on 2023-01-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_prod_net_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_prod_total',
        ),
    ]
